baseURL: https://domainname.pub/
title: "Domain Name Publication"
languageCode: zh-cn
theme: kidlat
defaultContentLanguage: zh-cn

outputs:
  home:
  - html
  - rss
  section:
  - html
  - rss
  taxonomy:
  - html
  term:
  - html

permalinks:
  news: /news/:filename/
  opinion: /opinion/:filename/
  page: /:filename/

params:
  short_title: Domain Name Publication
  display_name: Domain Name Publication
  license: CC BY-SA 4.0
  license_url: https://dftg.net/
  description: "Domain Name Publication"
  logo: /dnlogo.png
  footer: <span><a href="https://dftg.net/" target="_blank">DFTG</a></span>  <span><a href="#top">▲</a></span>

markup:
  goldmark:
    renderer:
      unsafe: true
      
#minify:
#  minifyOutput: true  