ignoreFiles = ["content/portfolio/\\.*","content/product/\\.*","content/sketch/\\.*","content/homepage/\\.*","content/post/\\.*","content/\\.*"] # disable example pages as this is a single page
baseURL = "https://domainname.pub"
languageCode = "zh-CN"
title = "DomainName Publication"
theme = "startpage"
copyright = "Sebastian Pech"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true

[pagination]
  pagerSize = 5

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[params.author]  
  name = "Sebastian Pech"

[params]
  description = "DomainName Publication"
  #images = ["logo.jpg"]
  startPageColumns = true
  welcomeText = "DomainName Publication"

[[params.searchEngines]]
  name = "Bing"
  activated = true
  url = "https://www.bing.com/search"


[taxonomies]
